export default {
  title: 'External Dependencies Documentation',
  description:
    "This document was generated by [**docdep**](https://www.github.com/Kuatsu/docdep), a tool to automagically generate documentation of your project's dependencies.",
  dependencies: {
    title: 'Dependencies ({{count}})',
    devTitle: 'Development Dependencies ({{count}})',
    devTitleHelper:
      'These dependencies are only used for development purposes and are not included in production builds.',
    name: 'Name',
    version: 'Version',
    license: 'License',
    description: 'Description',
  },
};
